---
title: "CMSY 2017 method"
author: "Seleni Cruz"
date: "October 31, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages 
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(plotly)
  library(fishmethods)
  library(devtools)
  devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})
```
#Loading datset of 7 species with catch data and catch inflated to 20%, 40% and 60% unreported catch 

MT - regular yearly catch 
MT_20 - inflated to 20% unreported catch
MT_40- inflated to 40% unreported catch
MT_60 - inflated to 60% unreported catch


```{r}

focalspeciescatch<-read.csv(here("docs", "focalspeciescatch.csv"))

#create a new dataframe to isolate your species of interest 
octopus<-focalspeciescatch%>%
  filter(NombreCientifico=="Octopus sp")

#Create vectors for the cmsy2 function
year <- c(octopus$Ano)
catch <- c(octopus$MT)
catch20<- c(octopus$MT_20)
catch40<- c(octopus$MT_40)
catch60<- c(octopus$MT_60)
```

#Running the model 

```{r}

?cmsy2

#Regular landings 
octopus <- cmsy2(year=year, catch=catch, resilience = "Medium")

plot_dlm(octopus)

#Landings inflated 20%
octopus20 <- cmsy2(year=year, catch=catch20, resilience = "Medium")

plot_dlm(octopus20)

#Landings inflated 40%
octopus40 <- cmsy2(year=year, catch=catch40, resilience = "Medium")

plot_dlm(octopus40)

#Landings inflated 60%
octopus60 <- cmsy2(year=year, catch=catch60, resilience = "Medium")

plot_dlm(octopus60)
```

