---
title: "CMSY2 All Species"
author: "Seleni Cruz"
date: "November 13, 2018"
output: html_document
---
#Packages 
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(dplyr)
  library(devtools)
  devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})
```


```{r, message=FALSE}
focalspeciescatch<-read.csv(here::here("docs", "focalspeciescatch.csv"))
```


#Octopus 
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Octopus sp")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Medium", verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

reg$ref_ts
reg$ref_pts
one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Medium", verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Medium", verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Medium", verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy, bmsy, last)

Octopus<- rbind(one, two, three, four)%>%
  mutate(Species="Octopus sp", CommonName="Octopus", Catch=c(0,20, 40, 60))

```

#Burrito Grunt 
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Anisotremus interruptus")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)
?cmsy2

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Low", r.low=0.318888609967242, r.hi=0.724876915433526, verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Low", r.low=0.318888609967242, r.hi=0.724876915433526, verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Low", r.low=0.318888609967242, r.hi=0.724876915433526, verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Medium", r.low=0.318888609967242, r.hi=0.724876915433526, verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy, bmsy, last)

Burrito<- rbind(one, two, three, four)%>%
  mutate(Species="Anisotremus interruptus", CommonName="Burrito grunt", Catch=c(0,20, 40, 60))

```

#Finescale Triggerfish
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Balistes polylepis")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Low", r.low=0.510363657443221, r.hi=1.12617893844454, verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Low", r.low=0.510363657443221, r.hi=1.12617893844454, verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Low", r.low=0.510363657443221, r.hi=1.12617893844454, verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Low", r.low=0.510363657443221, r.hi=1.12617893844454, verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy,bmsy, last)

Trigger<- rbind(one, two, three, four)%>%
  mutate(Species="Balistes polylepis", CommonName="Finescale triggerfish", Catch=c(0,20, 40, 60))

```

#Sawtail grouper
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Mycteroperca prionura")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy, bmsy, last)

Sawtail<- rbind(one, two, three, four)%>%
  mutate(Species="Mycteroperca prionura", CommonName="Sawtail grouper", Catch=c(0,20, 40, 60))

```

#Gulf grouper
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Mycteroperca jordani")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Very low", r.low=0.0669271491709394, r.hi=0.550459886988525, verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy, bmsy, last)

Gulf<- rbind(one, two, three, four)%>%
  mutate(Species="Mycteroperca jordani", CommonName="Gulf grouper", Catch=c(0,20, 40, 60))

```

#Bumphead parrotfish
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Scarus perrico")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Medium", r.low=0.232709817874126, r.hi=1.34975662886381, verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Medium", r.low=0.232709817874126, r.hi=1.34975662886381, verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Medium", r.low=0.232709817874126, r.hi=1.34975662886381, verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Medium", r.low=0.232709817874126, r.hi=1.34975662886381, verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy, bmsy, last)

Bump<- rbind(one, two, three, four)%>%
  mutate(Species="Scarus perrico", CommonName="Bumphead parrotfish", Catch=c(0,20, 40, 60))

```

#Yellow snapper
```{r}
species<-focalspeciescatch%>%
  filter(NombreCientifico=="Lutjanus argentiventris")

year <- c(species$Ano)
catch <- c(species$MT)
catch20<- c(species$MT_20)
catch40<- c(species$MT_40)
catch60<- c(species$MT_60)

#Regular landings 
reg <- cmsy2(year=year, catch=catch, resilience = "Low", r.low=0.197250203660337, r.hi=0.471264022674757, verbose = FALSE)
r<-reg$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-reg$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-reg$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-reg$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-reg$ref_ts[,]%>% tail(1)

one<-cbind(r, k, msy, bmsy, last)

#Landings inflated 20%
sp_20 <- cmsy2(year=year, catch=catch20, resilience = "Low", r.low=0.197250203660337, r.hi=0.471264022674757, verbose = FALSE)
r<-sp_20$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_20$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_20$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_20$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_20$ref_ts[,]%>% tail(1)

two<-cbind(r, k, msy, bmsy, last)

#Landings inflated 40%
sp_40 <- cmsy2(year=year, catch=catch40, resilience = "Low", r.low=0.197250203660337, r.hi=0.471264022674757, verbose = FALSE)
r<-sp_40$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_40$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_40$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_40$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_40$ref_ts[,]%>% tail(1)

three<-cbind(r, k, msy, bmsy, last)

#Landings inflated 60%
sp_60 <- cmsy2(year=year, catch=catch60, resilience = "Low", r.low=0.197250203660337, r.hi=0.471264022674757, verbose = FALSE)
r<-sp_60$ref_pts[1,2:4]%>% rename(r=est, r_lo=lo, r_hi=hi)
k<-sp_60$ref_pts[2,2:4]%>%rename(k=est, k_lo=lo, k_hi=hi)
msy<-sp_60$ref_pts[3,2:4]%>%rename(msy=est, msy_lo=lo, msy_hi=hi)
bmsy<-sp_60$ref_pts[5,2:4]%>%rename(bmsy=est, bmsy_lo=lo, bmsy_hi=hi)
last<-sp_60$ref_ts[,]%>% tail(1)

four <-cbind(r, k, msy, bmsy, last)

Yellow<- rbind(one, two, three, four)%>%
  mutate(Species="Lutjanus argentiventris", CommonName="Yellow snapper", Catch=c(0,20, 40, 60))

```


#Aggregate 

```{r}
cmsy2_priors<- rbind(Octopus, Burrito, Trigger, Sawtail, Gulf, Bump, Yellow)

cmsy2_priors<-cmsy2_priors[, c(35,36,37, 1:34)]

write.csv(cmsy2_priors, "cmsy2_priors.csv")
```

