---
title: "FS_TriggerFish_CMSY_Free"
author: "Edaysi Bucio"
date: "31 de octubre de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages 

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(plotly)
  library(fishmethods)
  library(devtools)
  devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})

```

#Loading datset of 7 species with catch data and catch inflated to 20%, 40% and 60% unreported catch 

MT - regular yearly catch 
MT_20 - inflated to 20% unreported catch
MT_40- inflated to 40% unreported catch
MT_60 - inflated to 60% unreported catch

```{r}

focalspeciescatch<-read.csv(here("docs", "focalspeciescatch.csv"))


#create a new dataframe to isolate your species of interest 

FS_Triggerfish<-focalspeciescatch%>%
  filter(NombreCientifico=="Balistes polylepis")


#Create vectors for the cmsy2 function
year <- c(FS_Triggerfish$Ano)
catch <- c(FS_Triggerfish$MT)
catch20<- c(FS_Triggerfish$MT_20)
catch40<- c(FS_Triggerfish$MT_40)
catch60<- c(FS_Triggerfish$MT_60)

```

#Running the model 
```{r}

#Regular landings 
FS_Triggerfish_CMSY <- cmsy2(year=year, catch=catch, resilience = "Low")
plot_dlm(FS_Triggerfish_CMSY)



#Landings inflated 20%

FS_Triggerfish_CMSY20 <- cmsy2(year=year, catch=catch20, resilience = "Low")
plot_dlm(FS_Triggerfish_CMSY20)



#Landings inflated 40%

FS_Triggerfish_CMSY40 <- cmsy2(year=year, catch=catch40, resilience = "Low")
plot_dlm(FS_Triggerfish_CMSY40)

#Landings inflated 60%

FS_Triggerfish_CMSY60 <- cmsy2(year=year, catch=catch60, resilience = "Low")
plot_dlm(FS_Triggerfish_CMSY60)
FS_Triggerfish_CMSY60

```




