---
title: "CMSY2_Saw_Tail_Grouper"
author: "Valeria Tamayo Cañadas"
date: "1/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Packages 

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(plotly)
  library(fishmethods)
  library(devtools)
  devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})


```


## Database

```{r}

focalspeciescatch<-read.csv(here("docs", "focalspeciescatch.csv"))
unique(focalspeciescatch$NombreCientifico) #7 species  

View(focalspeciescatch)

#create a new dataframe to isolate your species of interest 

saw_tail_grouper <- focalspeciescatch%>% 
  filter(NombreCientifico == "Mycteroperca prionura")

#Create vectors for the cmsy2 function

year <- c(saw_tail_grouper$Ano)
catch <- c(saw_tail_grouper$MT)
catch20<- c(saw_tail_grouper$MT_20)
catch40<- c(saw_tail_grouper$MT_40)
catch60<- c(saw_tail_grouper$MT_60)

```


##Running cMSY model

```{r}
saw_tail_grouperM <- cmsy2(year=year, catch=catch, resilience = "Very low")

plot_dlm(saw_tail_grouperM)
saw_tail_grouperM$ref_pts
saw_tail_grouperM$ref_ts
#Landings inflated 20%

saw_tail_grouperM20 <- cmsy2(year=year, catch=catch20, resilience = "Very low")

plot_dlm(saw_tail_grouperM20)
saw_tail_grouperM20$ref_pts
saw_tail_grouperM20$ref_ts

#Landings inflated 40%

saw_tail_grouperM40 <- cmsy2(year=year, catch=catch40, resilience = "Very low")
plot_dlm(saw_tail_grouperM40)
saw_tail_grouperM40$ref_pts
saw_tail_grouperM40$ref_ts

#Landings inflated 60%

saw_tail_grouperM60 <- cmsy2(year=year, catch=catch60, resilience = "Very low")
plot_dlm(saw_tail_grouperM60)
saw_tail_grouperM60$ref_pts
saw_tail_grouperM60$ref_ts
#Bmsy = 18.5
```
\
