---
title: "Aggregated by Genera"
author: "Seleni Cruz"
date: "October 23, 2018"
output:
  html_document:
    df_print: paged
  papersize: legal
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
   library(tidyr)
  library(stringr)
  library(ggplot2)
  library(dplyr)
  library(plotly)
  library(reshape)
})
```


```{r, include=FALSE}
LandingSites<- read.csv (here::here("raw_data", "landingsites.csv"))%>%
  filter(Confirmado=="y")

All_Genus<-read.csv(here::here("raw_data", "Focal_sp_Genus.csv")) #All values in USD/MT

catch<- readRDS (here::here("raw_data", "conapesca.RDS"))

catch<- catch %>%
  filter(Estado=="Baja california"| Estado=="Sonora")%>%
  filter(!(NombrePrincipal=="Macarela"|NombrePrincipal=="Sardina"|NombrePrincipal=="Camaron"|NombrePrincipal=="Corvina"|NombrePrincipal=="Calamar"|NombrePrincipal=="Anchoveta"))%>%
  merge(LandingSites, by="SitioDesembarque")%>%
  tidyr::separate(NombreCientifico,into="Genus", sep=" ", extra='drop', remove=FALSE)%>%
  mutate_at(.vars = "Genus", .funs = gsub, pattern = " spp", replacement = "")%>%
  merge(All_Genus, by="Genus")

catch_genus<-catch%>%
  group_by(Genus, Ano)%>%
  summarize(MT=sum(PesoVivo)/1000)%>%
  mutate(MT_20= MT*1.2, MT_40= MT*1.4, MT_60=MT*1.6)%>%
  filter(length(unique(Ano))>5|length(unique(Ano))==5)

length(unique(catch_genus$Genus)) #33 Genera

unique(catch_genus$Genus)

#write.csv(catch_genus, file = file.choose(new = T))

detail_genus<-catch%>%
  filter(Genus== "Seriola"| Genus=="Cynoscion")
length(unique(detail_genus$Ano))

detail_genus<-catch%>%
  filter(Genus== "Anisotremus"| Genus=="Atrina" | Genus=="Balistes" | Genus=="Bodianus" | Genus== "Callinectes" | Genus=="Caranx"| Genus=="Carcharhinus"| Genus=="Caulolatilus"| Genus=="Cephalopholis"| Genus=="Dasyatis" | Genus=="Epinephelus"| Genus=="Haemulon"| Genus== "Lutjanus"  | Genus== "Megapitaria" | Genus== "Merluccius"  | Genus== "Microlepidotus" | Genus=="Micropogonias" | Genus== "Mugil"| Genus=="Mycteroperca" | Genus=="Nematistius" | Genus=="Octopus" | Genus=="Panulirus"   | Genus=="Paralabrax"| Genus==  "Rhinobatos"   | Genus==  "Scarus"| Genus==   "Scomberomorus"  | Genus== "Scorpaena"  | Genus== "Sphoeroides"| Genus== "Sphyraena"    | Genus== "Sphyrna" | Genus==  "Squatina"  | Genus=="Strombus"    | Genus==   "Trachinotus")

summary<-detail_genus%>%
  group_by(Genus)%>%
  summarize(MT=sum(PesoVivo)/1000, 
            species=length(unique(NombreCientifico)), 
            years=length(unique(Ano)))

sum(detail_genus$MT)

specieslevel<- detail_genus%>%
  group_by(Genus, NombreCientifico)%>%
  summarize(MT=sum(MT))

```


```{r, echo=FALSE}

graph1<-ggplot(catch_genus, aes(x=Ano, y=MT, color=NombreCientifico))+
  tiff('yearly_catch_focal_species.tiff', units="in", width=10, height=5, res=300)+
 geom_line(size=1)+
  geom_point()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Catch series of 33 Genera", subtitle= "2000-2015")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))
#graph1

#ggplotly(graph1)
```



```{r, fig.width=15, fig.height=20, echo=FALSE}
graph2<-graph1+
   facet_wrap(~ NombreCientifico, scales = "free_y", ncol=2)
  #tiff('cacthbygenus.tiff', units="in", width=10, height=12, res=300)

ggplotly(graph2)
```

```{r, echo=FALSE, include=FALSE}
grouper<-catch_genus%>%
  filter(NombreCientifico=="Caulolatilus")

ggplot(grouper, aes(x=Ano, y=MT, color=NombreCientifico))+
  geom_line()+
  theme_classic()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Yearly Catch of two Epinephelus grouper species ", subtitle= "2000-2015")

#ggplotly(grouper)

```

