---
title: "CMSY_Priors_GulfGrouper_Free"
author: "Juliette Verstaen"
date: "11/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages 

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(sf)
  library(rfishbase)
  library(plotly)
  library(fishmethods)
  library(devtools)
 devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})


```


```{r}
harvest <- function(fishing, patches, MPA.width)  {
   fishing.vec <- vector(length=patches)
   fishing.vec[] <- fishing 
   if (MPA.width > 0) {  
      MPA.begin <- round((patches-MPA.width)/2)+1
      MPA.end <- MPA.begin + MPA.width -1         
      fishing.vec[MPA.begin:MPA.end] <- 0        
   }
   return(fishing.vec)
}
#harvest(fishing=0.5, patches=20, MPA.width =5) 
```


#MPA Model 

```{r}
MPA.model <- function(r, K, fishing, B0, patches, years, MPA.width, mrate) {
     fishing.vec <- harvest(fishing=fishing, patches=patches, MPA.width=MPA.width)
     biomass <- vector(length=patches) 
     biomass[]<-B0
     left.patch<- c(patches, 1: (patches-1))
     right.patch<- c(2: patches, 1) 
  
     summary<-vector(length=5)
     summary.output=summary

   for (i in 1:years) {
      leaving<-2*mrate*biomass
      arriving<-0.5*leaving[left.patch]+ 0.5*leaving[right.patch]
      surplus<- r*biomass *(1-biomass/K)
      catches<- fishing.vec*biomass
      biomass<-biomass+surplus-catches- leaving+ arriving
      
      summary=cbind(leave=sum(leaving), arrive=sum(arriving), surplus = sum(surplus), catch=sum(catches), biomass = sum(biomass))
      summary.output= rbind (summary.output, summary)
   }
    return(summary.output) 
}

MPA_octopus <- MPA.model(r=0.566, 
                 K=12170,
                 B0=1212.963, 
                 fishing=0.1, 
                 patches=100,
                 MPA.width=5,
                 years=16, 
                 mrate=0.5)

NoMPA_octopus <- MPA.model(r=0.566,
                   K=12170, 
                   B0=1212.96, 
                   fishing=0.1, 
                   patches=100,
                   MPA.width=0, 
                   years=16, 
                   mrate=0.5) 

```


```{r}

MPA_octopus.df <- data.frame(MPA_octopus[-1,])%>%
  mutate(year=c(2015:2030), State="MPA")

NoMPA_octopus.df <- data.frame(NoMPA_octopus[-1,])%>%
    mutate(year=c(2015:2030), State="No_MPA")

merge_octopus <- rbind(MPA_octopus.df, NoMPA_octopus.df)

#merge_octopus_1 <- filter(merge_octopus, catch != "NaN")

biomass_octopus_graph <- ggplot(data = merge_octopus, aes(x = year, y = biomass, colour = State))+
  geom_point()+
  geom_line()+
  labs(x="Year", y="Projected biomass (MT)")+
  theme_classic()+
  theme(legend.title=element_blank())+
  ggtitle("Octopus Predicted Biomass 2015-2030")




sum_bio_mpa_octo <-cumsum(MPA_octopus.df$biomass)

sum_bio_nompa_octo <- cumsum(NoMPA_octopus.df$biomass)

diff_mpa_biomass <- sum_bio_mpa_octo-sum_bio_nompa_octo
diff_mpa_biomass

total_biomass <- sum(diff_mpa_biomass)
total_biomass

```



```{r}
catch_ocotopus_graph <- ggplot(data = merge_octopus, aes( x = year, y = catch, colour = State))+
  geom_point()+
  geom_line()+
  labs(x="Year", y="Projected catch (MT)")+
  theme_classic()+
  theme(legend.title=element_blank())+
  ggtitle("Octopus Predicted Catch 2015-2030")

ggplotly(catch_ocotopus_graph)
        

sum_catch_mpa_octo <-cumsum(MPA_octopus.df$catch)

sum_catch_nompa_octo <- cumsum(NoMPA_octopus.df$catch)

diff_mpa_catch <- sum_catch_mpa_octo-sum_catch_nompa_octo
diff_mpa_catch

total_biomass <- sum(diff_mpa_catch)
total_biomass
```


















