---
title: "Triggerfish_priors"
author: "Edaysi Bucio"
date: "27 de noviembre de 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}

suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(sf)
  library(rfishbase)
  library(plotly)
  library(fishmethods)
  library(devtools)
 devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})

```

# Functions
```{r}

harvest <- function(fishing, patches, MPA.width) {

fishing.vec <- vector(length=patches)

fishing.vec[] <- fishing 

if (MPA.width > 0) { 

MPA.begin <- round((patches-MPA.width)/2)+1

MPA.end <- MPA.begin + MPA.width -1 

fishing.vec[MPA.begin:MPA.end] <- 0 

}

return(fishing.vec)

}

#harvest(fishing=0.5, patches=20, MPA.width =5) 
```

#MPA model
```{r}

MPA.model <- function(r, K, fishing, B0, patches, years, MPA.width, mrate) {

fishing.vec <- harvest(fishing=fishing, patches=patches, MPA.width=MPA.width)

biomass <- vector(length=patches) 

biomass[]<-B0

left.patch<- c(patches, 1: (patches-1))

right.patch<- c(2: patches, 1) 



summary<-vector(length=5)

summary.output=summary



for (i in 1:years) {

leaving<-2*mrate*biomass

arriving<-0.5*leaving[left.patch]+ 0.5*leaving[right.patch]

surplus<- r*biomass *(1-biomass/K)

catches<- fishing.vec*biomass

biomass<-biomass+surplus-catches- leaving+ arriving



summary=cbind(leave=sum(leaving), arrive=sum(arriving), surplus = sum(surplus), catch=sum(catches), biomass = sum(biomass))

summary.output= rbind (summary.output, summary)


}

return(summary.output) 

}


MPA_TriggerFish <- MPA.model(r=0.58860, 

                 K=24,

                 B0=459.4605, 

                 fishing=0.1, 

                 patches=100,

                 MPA.width=5,

                 years=11, 

                 mrate=0.5)



NoMPA_TriggerFish <- MPA.model(r=0.326,

                   K=681.09, 

                   B0=459.4605, 

                   fishing=0.1, 

                   patches=100,

                   MPA.width=0, 

                   years=11, 

                   mrate=0.5) 



```

#Data frame

```{r}

MPA_TriggerFish.df <- data.frame(MPA_gulf_grouper[-1,])%>%

  mutate(year=c(2015:2025), State="MPA")



NoMPA_TriggerFish.df <- data.frame(NoMPA_gulf_grouper[-1,])%>%

    mutate(year=c(2015:2025), State="No_MPA")



merge_TriggerFish <- rbind(MPA_gulf_grouper.df, NoMPA_gulf_grouper.df)



#PLOT
ggplot(data = merge_TriggerFish, aes(x = year, y = biomass, colour = State))+

  geom_point()+

  geom_line()+

  labs(x="Year", y="Projected biomass (MT)")+

  theme_classic()+

  theme(legend.title=element_blank())


ggplot(data = merge_TriggerFish, aes( x = year, y = catch, colour = State))+

  geom_point()+

  geom_line()+

  labs(x="Year", y="Projected catch (MT)")+

  theme_classic()+

  theme(legend.title=element_blank())



```

