---
title: "MSY"
author: "Edaysi Bucio"
date: "23 de octubre de 2018"
output: html_document
---

```{r Packages}

#Burrito grunt and Fine scale triggerfish

library(tidyverse) 
  library(here)
  library(ggplot2) 
  library(dplyr) 
  library(sf) 
  library(rfishbase) 
  library(plotly) 
  library(fishmethods) 
  library(devtools) 
install_github("James-Thorson/FishLife") 
library(FishLife) 

```

# Selecting the specie

```{r }

#loading catch data of 6 species with more than 5 years of catch data, detailed code for this dataset is in the "landing sites.rmd" in docs  

focalspeciescatch<-read.csv(here("docs", "focalspeciescatch.csv"))

unique(focalspeciescatch$NombreCientifico) #6 species  

View(focalspeciescatch)

#Specie

burrito <- focalspeciescatch%>% 
  filter(NombreCientifico == "Anisotremus interruptus")
```

#Graphs 

```{r}

graph <-ggplot(burrito, aes(x=Ano, y=MT))+ 
  geom_line(size=1)+ 
  ggtitle("Burrito grunt")+ 
  geom_point()+ 
  geom_line()+ 
  labs(x="Year", y="Yearly total catch catch (MT)")+ 
  theme_classic()+ 
  scale_x_continuous(expand=c(0,0))+ 
  scale_y_continuous(expand=c(0,0))+ 
  theme(legend.title=element_blank()) 

ggplotly(graph) 

```


# Catch MSY

```{r}

year_burrito<-c(burrito$Ano) #vector of years 
 
catch_burrito<-c(burrito$MT) #vector of catch date 

View(burrito)


#Initial catch divided by highest catch; use ranges listed in the Martell publication based on this ratio 
 
ICB = 1.4373/5.3456
#ICB = 0.2688753

#final year catch divided by highest catch; use ranges listed in the Martell publication based on this ratio 

FCB = 0.9207/5.3456
#FCB =  0.1722351


## Catch MSY model information

burrito_trial <- catchmsy(year=year_burrito,
                catch=catch_burrito,
    l0=list(low=0.3,up=0.6,step=0),#biomass in year in relation to K, ICB
    lt=list(low= 0.01,up=0.4,refyr=2014),#biomass in last year in relation to K, years catch divided by highest catch 
    k=list(dist="unif",low=5.3456,up=534.56), #carrying capacity; low=highest reported catch, high=highest catch*100 
    r=list(dist="unif",low=0.05,up=.5), #intrinsic growth rate based on resiliene  #Resilience:Low 
    M=list(dist="unif",low=0.1,up=0.9), #Natural mortality  
    nsims=30000, #Monte carlo simulations  
    catchout = (1), #saving the monte carlo simulations that can later be graphed 
    grout = 1, #output just to console, 
    graphs = c(1, 2,3,4,5,6,7,8,9,10,11)) 

burrito_trial

```

