---
title: "Kobe Plots and Historical Fishing"
author: "Seleni Cruz"
date: "January 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, message=FALSE}
library(ggplot2)
library(here)
library(plotly)
library(tidyverse)
library(gganimate)
library(ggrepel)
library(ggridges)
```

OA Eq at 0.3 B/Bmsy
```{r}
Genus<- read.csv (here::here("data", "Genus_2D_patchmodel0.3.csv"))%>%
  filter(Adjusted=="MT")%>%
  select (Name, Year, Biomass_est, Catch_est, Fishing_est, Status)

fmsy_bmsy<- read.csv(here::here("data", "Genus_pts.csv"))%>%
  filter(!(Name== "Caranx"))%>%
  filter(Adjusted=="MT")%>%
  select (Name, msy, bmsy, fmsy)

kobe_data <- merge (Genus, fmsy_bmsy, by="Name")%>%
  mutate (bbmsy= Biomass_est/bmsy, ffmsy= Fishing_est/fmsy)

bmsy<- expression(paste(B/B[MSY]))
fmsy <- expression(paste(F/F[MSY]))

MPA<- kobe_data%>%
  filter(Status=="MPA 2015")%>%
  filter(!(Name=="Epinephelus"))
NoMPA<-kobe_data%>%
  filter(Status=="No MPA")%>%
   filter(!(Name=="Epinephelus"))

kobe_MPA<-ggplot(MPA, aes(x = bbmsy, y = ffmsy, group = Name)) +
  geom_point(aes(color = Year), size = 3, show.legend=FALSE) +
  labs(title = "Marine reserve network: {closest_state} ", x = bmsy, y= fmsy) +
  scale_color_gradientn(colors = c("chocolate","darkblue")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = 0.5, state_length = 0.05,  wrap=FALSE) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade() +
  shadow_mark()

?transition_states

animate(kobe_MPA, nframes = 60, renderer = gifski_renderer("kobe_MPA0.3.gif", loop=FALSE))

#kobe_MPA<- ggplot(MPA, aes(x = bbmsy, y = ffmsy, group=Name)) +
  geom_rect(xmin = 0.0, xmax = 1.0, ymin = 0.0, ymax = 1, fill = 'yellow', alpha = 0.1) +
  geom_rect(xmin = 0, xmax = 1, ymin = 1.0, ymax = 2.5, fill = 'red', alpha = 0.1) +
  geom_rect(xmin = 1, xmax = 2.1, ymin = 0, ymax = 1, fill = 'green', alpha = 0.1) +
  geom_rect(xmin = 1, xmax = 2.1, ymin = 1, ymax = 2.5, fill = 'orange', alpha = 0.1)+
  geom_line(size = 1, show.legend = FALSE) +
  labs(title = "Marine Reserve Network Scenario: {frame_along} ", x = bmsy, y= fmsy) +
  scale_color_gradientn(colors = c("black","black")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_reveal(id = Name, along = Year) + 
  ease_aes('quadratic-in-out')+
    theme_classic(base_size = 20)

#animate(kobe_MPA, nframes = 100, renderer = gifski_renderer("kobe_MPA0.3.gif", loop=FALSE))

kobe_no<-ggplot(NoMPA, aes(x = bbmsy, y = ffmsy)) +
  geom_point(aes(color = Year), size = 3, show.legend=FALSE) +
  labs(title = "Business as usual: {closest_state} ", x = bmsy, y= fmsy) +
  scale_color_gradientn(colors = c("chocolate","darkblue")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = -.5, state_length = 0.05,  wrap=FALSE) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade() +
  shadow_mark()


animate(kobe_no, nframes = 60, renderer = gifski_renderer("kobe_no0.3.gif", loop=FALSE))

```



```{r}
Genus_pts<- read.csv(here::here("data", "Genus_pts.csv"))%>%
  filter(!(Name== "Caranx"))%>%
  filter(Adjusted=="MT")%>%
  select(Name, Year, bbmsy, ffmsy)
  

MPA<- kobe_data%>%
  filter(Status=="MPA 2015")%>%
  select(Name, Year, bbmsy, ffmsy)%>%
  rbind(Genus_pts)

NoMPA<-kobe_data%>%
   filter(Status=="No MPA" & Year==2035)%>%
  select(Name, Year, bbmsy, ffmsy)

kobe_MPA<-ggplot(MPA, aes(x = bbmsy, y = ffmsy, group = Name)) +
  geom_point(aes(color = Year), size = 3, show.legend=FALSE) +
  labs(title = "Marine reserve network: {closest_state} ", x = "B/BMSY", y= "F/FMSY") +
  scale_color_gradientn(colors = c("chocolate","darkblue")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = 30, state_length = 1,  wrap=FALSE) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade()

kobe_MPA
```



#How does this change over projected time in MPA and No MPA scenario 
Scenaio where OA eq is at 10% of b/bmsy
```{r, echo=FALSE, include =FALSE}

fmsy_bmsy<- read.csv(here::here("data", "Genus_pts.csv"))%>%
  filter(!(Name== "Caranx"))%>%
  filter(Adjusted=="MT")%>%
  select (Name, msy, bmsy, fmsy)

Genus<- read.csv (here::here("data", "Genus_2D_patchmodel0.1.csv"))%>%
  filter(Adjusted=="MT")%>%
  select (Name, Year, Biomass_est, Catch_est, Fishing_est, Status)

kobe_data <- merge (Genus, fmsy_bmsy, by="Name")%>%
  mutate (bbmsy= Biomass_est/bmsy, ffmsy= Fishing_est/fmsy)

MPA<- kobe_data%>%
  filter(Status=="MPA 2015")
NoMPA<-kobe_data%>%
  filter(Status=="No MPA")

kobe_MPA<-ggplot(MPA, aes(x = bbmsy, y = ffmsy)) +
  geom_point(aes(color = Year), size = 3, show.legend=FALSE) +
  labs(title = "Year: {closest_state} ", x = "B/BMSY", y= "F/FMSY") +
  scale_color_gradientn(colors = c("chocolate","darkblue")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = 30, state_length = 10) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade() +
  shadow_mark()


animate(kobe_MPA, nframes = 100, renderer = gifski_renderer("kobe_MPA0.1.gif"))
?animate

kobe_no<-ggplot(NoMPA, aes(x = bbmsy, y = ffmsy)) +
  geom_point(aes(color = Year, size=3)) +
  labs(title = "Fishery Status: {closest_state} ", x = "B/BMSY", y= "F/FMSY", subtitle = "Open access eq at 0.10 B/BMSY") +
  theme_classic()+
  scale_color_gradientn(colors = c("black","purple","orange","yellow")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = 2, state_length = 2) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade() +
  shadow_mark()

animate(kobe_no, nframes = 100, renderer = gifski_renderer("kobe_no0.1.gif"))



```









```{r}
Genus<- read.csv (here::here("data", "Genus_2D_patchmodel0.csv"))%>%
  filter(Adjusted=="MT")%>%
  select (Name, Year, Biomass_est, Catch_est, Fishing_est, Status)

kobe_data <- merge (Genus, fmsy_bmsy, by="Name")%>%
  mutate (bbmsy= Biomass_est/bmsy, ffmsy= Fishing_est/fmsy)

MPA<- kobe_data%>%
  filter(Status=="MPA 2015")
NoMPA<-kobe_data%>%
  filter(Status=="No MPA")

kobe_MPA<-ggplot(MPA, aes(x = bbmsy, y = ffmsy)) +
  geom_point(aes(color = Year, size=3)) +
  labs(title = "Fishery Status with Reserves: {closest_state} ", x = "B/BMSY", y= "F/FMSY", subtitle = "Open access eq at 0.00 B/BMSY") +
  theme_classic()+
  scale_color_gradientn(colors = c("black","purple","orange","yellow")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = 2, state_length = 2) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade() +
  shadow_mark()

animate(kobe_MPA, nframes = 100, renderer = gifski_renderer("kobe_MPA0.0.gif"))

kobe_no<-ggplot(NoMPA, aes(x = bbmsy, y = ffmsy)) +
  geom_point(aes(color = Year, size = 3)) +
  labs(title = "Fishery Status without Reserves: {closest_state} ", x = "B/BMSY", y= "F/FMSY", subtitle = "Open access eq at 0.00 B/BMSY") +
  theme_classic()+
   scale_color_gradientn(colors = c("black","purple","orange","yellow")) +
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  transition_states(Year, transition_length = 2, state_length = 2) +
  theme_classic(base_size = 20)+
  enter_fade()+
  exit_fade() +
  shadow_mark()

animate(kobe_no, nframes = 100, renderer = gifski_renderer("kobe_no0.0.gif"))

```



#Historical fishing effort 
```{r, echo=FALSE, fig.height= 10, fig.width=7}
Fishing<- read.csv(here::here("data", "Genus_ts.csv"))%>%
  filter(Adjusted=="MT")%>%
  select(Name, year, f, fmsy)

graph1<-ggplot(Fishing, aes(x=year, y=f, color=Name))+ 
  geom_line(aes(y=f), size=0.4)+
  geom_line(aes(y=fmsy), size=0.3, color="black", linetype=2)+
  labs(x="Year", y="fishing mortality", title="Historical ishing mortality", subtitle= "2000-2015")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))

graph2<-graph1+
   facet_wrap(~ Name, scales = "free_y", ncol=2)

ggplotly(graph2)
```

