---
title: "SawTai_Grouper_BranchMPAModel"
author: "Valeria Tamayo Canadas"
date: "11/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
calc.harvest.vec <- function(u.out, ncells, MPA.width)  {
   u.vec <- vector(length=ncells) #create vector to store harvest rates in each cell hence the the length is ncells 
   u.vec[] <- u.out       #set every cell to u.out, equivalent to u.vec[1:ncells] <- u.out   
   if (MPA.width > 0) {   #no need to do this if there is no MPA! 
      MPA.begin <- round((ncells-MPA.width)/2)+1  #start cell of MPAin the middle of ncells 
      MPA.end <- MPA.begin + MPA.width -1         #end cell of MPA in the middle of ncells 
      u.vec[MPA.begin:MPA.end] <- 0        
   }
   return(u.vec)
}

calc.harvest.vec(u.out=0.5, ncells=100, MPA.width =5) 


```


Saw Tail Grouper
Average r and K values
Raw catch numbers, no estimate of illegal catch included
```{r}
MPA.model <- function(r, K, u.out, ncells, nsteps, 
                      MPA.width, mrate) {
   #harvest rate in each cell using function described in part 1
   u.vec <- calc.harvest.vec(u.out=u.out, ncells=ncells, MPA.width=MPA.width)
   
   #Population in each cell, empty cells place holder for later calcualtions 
   pop <- vector(length=ncells) 
   
   #set starting population in vector pop in each cell 
   # equal to K; this can be biomass estimate at first time step
    pop[]<-K
   
  # this models assumed pacman movement of individuals in the cells; where individuals moving off the right appear on the left and vice versa; there are other movement simulations that can be considered 
   #vector left.cells storing the cell numbers of cells to the left of each cell
   left.cell<- c(ncells, 1: (ncells-1))
    
   #vector right.cells storing the cell numbers of cells to the right of each cell
   right.cell<- c(2: ncells, 1) #Start at 2 since the fist cell (think corner) cannot move to the right, only to the left. the :1 wraps the area around 
   result<- vector(length=5)
   out=result
   summary<-vector(length=5)
   summary.output=summary
   #print(left.cell) #print allows you to see what the vectors look like to make sure they are right; not necessary when running simulations but are a good check 
   #print(right.cell)
   #print(u.vec)
   #print(pop)
   
   #plot the initial numbers
     plot(x=1:ncells, y=pop, xlab="Cell number", lwd=3,
        ylab="Population size", ylim=c(0, 1.05*max(pop)), 
        type="l", yaxs="i", xaxs="i")
   
   #loop through the time steps (nsteps or # of years)
   for (i in 1:nsteps) {
      #Vector "leaving" is number of individuals leaving each cell 
      #Number leaving each cell is 2*movement rate*pop size
     #since i used vector operation there is no need to loop 
      leaving<-2*mrate*pop
      #print(leaving)
      
      #The number of immigrants is 1/2 those leaving cells to the left and 1/2 those leaving cells to the right. 
      #The idea here is that individuals evely migrate to left and right cells
      arriving<-0.5*leaving[left.cell]+ 0.5*leaving[right.cell]
      #print(arriving)
      
      #surplus production from the logistic model
      surplus<- r*pop *(1-pop/K)
      #print (surplus)
      #catches = harvest rate in each cell times the population size 
      #basically how much are we catching at each time step
      catches<- u.vec*pop
      #print(catches)
      
      #Now that we caught some fish and some migrated we update the population numbers
      pop<-pop+surplus-catches- leaving+ arriving
      #print(pop)
      #plot the population in each cell (uncomment when ready); plot allows us to see what population numbers look like in each cell as the model steps through each time step. We should see higher population inside MPA since harvest rate is 0.
      
      lines(x=1:ncells, y=pop, lwd=(nsteps-i+1)/nsteps*3)
      
      #result is a list of surplus, catches and pop in each cell; more detail 
      result=cbind(leaving, arriving, surplus, catches, pop)
      #binds each time step
      out=cbind(out, result)
      
      #results of each variable summed across all cells in each time step
      summary=cbind(leave=sum(leaving), arrive=sum(arriving), sur = sum(surplus), catch=sum(catches), biomass = sum(pop))
      #Every row represents a time step ie a year 
      summary.output= rbind (summary.output, summary)
   }
    return(summary.output) # can change this to out for more details 
}

MPA_sawtailgrouper <- MPA.model(r=0.067, K=84.29, u.out=0.2485, ncells=100,
          MPA.width=5, nsteps=5, mrate=0.5)

NoMPA_sawtailgrouper <- MPA.model(r=0.067, K=84.29, u.out=0.2485, ncells=100,
          MPA.width=0, nsteps=5, mrate=0.5) #assuming no MPA MPA.width set to 0 everything else remains the same. I am not sure what to use for u.out, so i kept the number that the bumphead parrotfish.
```


```{r}
MPA_sawtailgrouper.df<- data.frame(MPA_sawtailgrouper[-1,])%>%
  mutate(year=c(2015:2019))%>%
  rename(c("leave"="MPAleave", "arrive"="MPAarrive", "sur"="MPAsurplus", "catch"= "MPAcatch", "biomass"="MPAbiomass"))
NoMPA_sawtailgrouper.df<-data.frame(NoMPA_sawtailgrouper[-1,])%>%
    mutate(year=c(2015:2019))

merge<-merge(MPA_sawtailgrouper.df, NoMPA_sawtailgrouper.df, by="year")

ggplot(data=merge, aes(x=year))+
  geom_line(aes(y=MPAbiomass), color="blue")+
  geom_line(aes(y=biomass), color="green")+
  geom_point(aes(y=MPAbiomass), color="blue")+
  geom_point(aes(y=biomass))+
  labs(x="Year", y="Projected biomass (MT)")+
  theme_classic()+
  theme(legend.title=element_blank())+
  ggtitle("Saw Tail Grouper Biomass")
```

